### ISSUE TITLE
Updated web build tools no longer will build web apps that use time_machine

### ISSUE THREAD

**Issue by rich-j** [Dana-Ferguson/time_machine#18]
In a web project, upgrading the `build_web_compilers` dev_dependency from: `^1.2.1` to `^2.1.0` causes the build (e.g. `webdev serve`) to not create the web application, instead we get this warning in the build:

    [WARNING] build_web_compilers:entrypoint on web/main.dart: Skipping compiling webapp|web/main.dart with ddc because some of its
    transitive libraries have sdk dependencies that not supported on this platform:

    time_machine|lib/src/timezones/tzdb_io.dart
    time_machine|lib/src/utility/binary_writer.dart
    resource|lib/src/resolve.dart

    https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings

    [INFO] Running build completed, took 25.2s

When we revert to `build_web_compilers: ^1.2.1` our web project builds and runs. The suggested ["help link"](https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings) doesn't seem to provide relevant advice.

Looking at the file `tzdb_io.dart` we see `import 'dart:io';`. This package is not supported on the web and seems to be the "sdk dependency" that the warning is referring to. It also doesn't seem to be used in that file, so a simple line deletion removes that source file from the above warning.

The file `binary_writer.dart` also imports `dart:io` but it is using `io` package functionality. The `timezones` directory has files that depend on `binary_writer.dart` but seem to not be needed for web support (they seem to be used for creating the `tzdb` file). Could this part of the system be restructured to not be a dependency for read-only (e.g. web and Flutter) uses?

It's not clear what the resolution will be for the `resource` package dependency. There are recent issues filed/updated: https://github.com/dart-lang/resource/issues/35 and also https://github.com/dart-lang/sdk/issues/37153. These seem to suggest removing support for the web altogether - although it seems that time_machine may not use the `resource` package for the web either.

**Comment by Dana-Ferguson** [comment]
This should be fixed now. Let me know if you're still having problems.

I apologize for getting back to this so late, life happened.

**Comment by rich-j** [comment]
Thanks, `time_machine: ^0.9.10` fixes the above build issues when building with the current `build_web_compilers: ^2.2.3`.
