### ISSUE TITLE
[Web] Get stuck at initialize call

### ISSUE THREAD

**Issue by jasonlaw** [Dana-Ferguson/time_machine#27]
Hi,

Is there any additional setup required to run this package in web?
It is working fine in the mobile app, but always get stuck at initialize call when running in flutter web.

Any help is appreciated.

**Comment by jamesblasco** [comment]
I get this errors: 

html_dart2js.dart:17407 GET http://localhost:54322/packages/time_machine/data/cultures/en-null.bin 404 (Not Found)

uncaught (in promise) Error: [object ProgressEvent]
    at Object.throw_ [as throw] (errors.dart:196)
    at async._AsyncCallbackEntry.new.callback (zone.dart:1114)
    at Object._microtaskLoop (schedule_microtask.dart:43)
    at _startMicrotaskLoop (schedule_microtask.dart:52)
    at async_patch.dart:168
DartError @ errors.dart:147
throw_ @ errors.dart:196
(anonymous) @ zone.dart:1114
_microtaskLoop @ schedule_microtask.dart:43
_startMicrotaskLoop @ schedule_microtask.dart:52
(anonymous) @ async_patch.dart:168
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:166
_scheduleImmediate @ async_patch.dart:138
_scheduleAsyncCallback @ schedule_microtask.dart:73
_rootScheduleMicrotask @ zone.dart:1187
scheduleMicrotask @ zone.dart:1401
[_asyncCompleteError] @ future_impl.dart:581
[_completeError] @ future_impl.dart:46
completeError @ future_impl.dart:29
(anonymous) @ html_dart2js.dart:17398
_checkAndCall @ operations.dart:326
dcall @ operations.dart:331
(anonymous) @ html_dart2js.dart:35657
load (async)
[_addEventListener] @ html_dart2js.dart:15094
[dartx.addEventListener] @ html_dart2js.dart:15082
[_tryResume] @ html_dart2js.dart:35709
_EventStreamSubscription.new @ html_dart2js.dart:35658
listen @ html_dart2js.dart:35558
request @ html_dart2js.dart:17384
_httpGetBytes @ web.dart:31
_readAsBytes @ web.dart:41
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
_readAsBytes @ web.dart:39
getBinary @ web.dart:76
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
getBinary @ web.dart:68
getCulture @ culture_io.dart:83
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
getCulture @ culture_io.dart:69
getCulture @ culture.dart:29
onValue @ async_patch.dart:47
runUnary @ zone.dart:1381
handleValue @ future_impl.dart:140
handleValueCallback @ future_impl.dart:682
_propagateToListeners @ future_impl.dart:711
[_completeWithValue] @ future_impl.dart:526
(anonymous) @ future_impl.dart:556
_microtaskLoop @ schedule_microtask.dart:43
_startMicrotaskLoop @ schedule_microtask.dart:52
(anonymous) @ async_patch.dart:168
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:166
_scheduleImmediate @ async_patch.dart:138
_scheduleAsyncCallback @ schedule_microtask.dart:73
_rootScheduleMicrotask @ zone.dart:1187
scheduleMicrotask @ zone.dart:1401
[_asyncComplete] @ future_impl.dart:555
complete @ future_impl.dart:42
(anonymous) @ html_dart2js.dart:17396
_checkAndCall @ operations.dart:326
dcall @ operations.dart:331
(anonymous) @ html_dart2js.dart:35657
load (async)
[_addEventListener] @ html_dart2js.dart:15094
[dartx.addEventListener] @ html_dart2js.dart:15082
[_tryResume] @ html_dart2js.dart:35709
_EventStreamSubscription.new @ html_dart2js.dart:35658
listen @ html_dart2js.dart:35558
request @ html_dart2js.dart:17384
getString @ html_dart2js.dart:17237
_readAsString @ web.dart:58
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
_readAsString @ web.dart:51
getJson @ web.dart:87
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
getJson @ web.dart:82
_loadCultureMapping @ culture_io.dart:47
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
_loadCultureMapping @ culture_io.dart:46
load @ culture_io.dart:15
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
load @ culture_io.dart:14
_cultures @ culture.dart:26
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
get _cultures @ culture.dart:26
getCulture @ culture.dart:29
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
getCulture @ culture.dart:29
load @ time_machine_delegate.dart:20
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
load @ time_machine_delegate.dart:19
_loadAll @ localizations.dart:58
load @ localizations.dart:510
initState @ localizations.dart:474
[_firstBuild] @ framework.dart:4456
mount @ framework.dart:4302
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
performRebuild @ framework.dart:4344
rebuild @ framework.dart:4048
[_firstBuild] @ framework.dart:4307
mount @ framework.dart:4302
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
performRebuild @ framework.dart:4344
rebuild @ framework.dart:4048
[_firstBuild] @ framework.dart:4307
[_firstBuild] @ framework.dart:4482
mount @ framework.dart:4302
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
performRebuild @ framework.dart:4344
rebuild @ framework.dart:4048
[_firstBuild] @ framework.dart:4307
mount @ framework.dart:4302
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
performRebuild @ framework.dart:4344
rebuild @ framework.dart:4048
[_firstBuild] @ framework.dart:4307
mount @ framework.dart:4302
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
performRebuild @ framework.dart:4344
rebuild @ framework.dart:4048
[_firstBuild] @ framework.dart:4307
mount @ framework.dart:4302
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
mount @ framework.dart:5570
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
performRebuild @ framework.dart:4344
rebuild @ framework.dart:4048
[_firstBuild] @ framework.dart:4307
mount @ framework.dart:4302
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
performRebuild @ framework.dart:4344
rebuild @ framework.dart:4048
[_firstBuild] @ framework.dart:4307
[_firstBuild] @ framework.dart:4482
mount @ framework.dart:4302
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
performRebuild @ framework.dart:4344
rebuild @ framework.dart:4048
[_firstBuild] @ framework.dart:4307
[_firstBuild] @ framework.dart:4482
mount @ framework.dart:4302
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
performRebuild @ framework.dart:4344
rebuild @ framework.dart:4048
[_firstBuild] @ framework.dart:4307
[_firstBuild] @ framework.dart:4482
mount @ framework.dart:4302
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
performRebuild @ framework.dart:4344
rebuild @ framework.dart:4048
[_firstBuild] @ framework.dart:4307
mount @ framework.dart:4302
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
performRebuild @ framework.dart:4344
rebuild @ framework.dart:4048
[_firstBuild] @ framework.dart:4307
[_firstBuild] @ framework.dart:4482
mount @ framework.dart:4302
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
performRebuild @ framework.dart:4344
rebuild @ framework.dart:4048
[_firstBuild] @ framework.dart:4307
mount @ framework.dart:4302
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
performRebuild @ framework.dart:4344
rebuild @ framework.dart:4048
[_firstBuild] @ framework.dart:4307
[_firstBuild] @ framework.dart:4482
mount @ framework.dart:4302
inflateWidget @ framework.dart:3297
updateChild @ framework.dart:3091
[_rebuild] @ binding.dart:1054
mount @ binding.dart:1025
(anonymous) @ binding.dart:968
buildScope @ framework.dart:2512
attachToRenderTree @ binding.dart:967
attachRootWidget @ binding.dart:847
(anonymous) @ binding.dart:830
internalCallback @ isolate_helper.dart:50
setTimeout (async)
_isolate_helper.TimerImpl.new @ isolate_helper.dart:57
_createTimer @ async_patch.dart:188
createTimer @ zone.dart:1405
new @ timer.dart:51
run @ timer.dart:91
scheduleAttachRootWidget @ binding.dart:829
runApp @ binding.dart:895
main$ @ main.dart:35
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
main$ @ main.dart:34
main$ @ main_web_entrypoint.dart:13
onValue @ async_patch.dart:47
runUnary @ zone.dart:1381
handleValue @ future_impl.dart:140
handleValueCallback @ future_impl.dart:682
_propagateToListeners @ future_impl.dart:711
(anonymous) @ future_impl.dart:391
_microtaskLoop @ schedule_microtask.dart:43
_startMicrotaskLoop @ schedule_microtask.dart:52
(anonymous) @ async_patch.dart:168
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:166
_scheduleImmediate @ async_patch.dart:138
_scheduleAsyncCallback @ schedule_microtask.dart:73
_rootScheduleMicrotask @ zone.dart:1187
scheduleMicrotask @ zone.dart:1401
[_asyncComplete] @ future_impl.dart:555
complete @ future_impl.dart:42
(anonymous) @ js_util.dart:150
Promise.then (async)
promiseToFuture @ js_util.dart:153
[dartx.load] @ html_dart2js.dart:15783
[_loadFontFace] @ font_collection.dart:184
registerAsset @ font_collection.dart:170
registerFonts @ font_collection.dart:70
onValue @ async_patch.dart:47
runUnary @ zone.dart:1381
handleValue @ future_impl.dart:140
handleValueCallback @ future_impl.dart:682
_propagateToListeners @ future_impl.dart:711
[_completeWithValue] @ future_impl.dart:526
(anonymous) @ future_impl.dart:556
_microtaskLoop @ schedule_microtask.dart:43
_startMicrotaskLoop @ schedule_microtask.dart:52
(anonymous) @ async_patch.dart:168
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:166
_scheduleImmediate @ async_patch.dart:138
_scheduleAsyncCallback @ schedule_microtask.dart:73
_rootScheduleMicrotask @ zone.dart:1187
scheduleMicrotask @ zone.dart:1401
[_asyncComplete] @ future_impl.dart:555
complete @ future_impl.dart:42
(anonymous) @ html_dart2js.dart:17396
_checkAndCall @ operations.dart:326
dcall @ operations.dart:331
(anonymous) @ html_dart2js.dart:35657
load (async)
[_addEventListener] @ html_dart2js.dart:15094
[dartx.addEventListener] @ html_dart2js.dart:15082
[_tryResume] @ html_dart2js.dart:35709
_EventStreamSubscription.new @ html_dart2js.dart:35658
listen @ html_dart2js.dart:35558
request @ html_dart2js.dart:17384
load @ assets.dart:38
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
load @ assets.dart:34
registerFonts @ font_collection.dart:28
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
registerFonts @ font_collection.dart:24
webOnlySetAssetManager @ initialization.dart:64
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
webOnlySetAssetManager @ initialization.dart:44
webOnlyInitializePlatform @ initialization.dart:24
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
webOnlyInitializePlatform @ initialization.dart:8
main$ @ main_web_entrypoint.dart:11
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
main$ @ main_web_entrypoint.dart:8
(anonymous) @ VM2038:1
runMain @ client.js:7952
(anonymous) @ client.js:23849
(anonymous) @ client.js:3003
call$2 @ client.js:10800
_asyncStartSync @ client.js:2968
$call$body$main__closure @ client.js:23861
call$1 @ client.js:23792
_rootRunUnary @ client.js:3303
runUnary$2$2 @ client.js:12130
runUnaryGuarded$1$2 @ client.js:12058
_sendData$1 @ client.js:11601
perform$1 @ client.js:11754
call$0 @ client.js:11807
_microtaskLoop @ client.js:3168
_startMicrotaskLoop @ client.js:3174
call$1 @ client.js:10675
invokeClosure @ client.js:1188
(anonymous) @ client.js:1207
childList (async)
call$1 @ client.js:10685
_scheduleAsyncCallback @ client.js:3187
_rootScheduleMicrotask @ client.js:3348
scheduleMicrotask @ client.js:3215
schedule$1 @ client.js:11789
_addPending$1 @ client.js:11592
_sendData$1 @ client.js:11411
add$1 @ client.js:11328
_onIncomingMessage$1 @ client.js:23399
eval @ VM2018:3
invokeClosure @ client.js:1188
(anonymous) @ client.js:1207
Show 182 more frames

**Comment by JulianKowalczuk** [comment]
@Dana-Ferguson, I found out solution how to fix it:
there is problem with path resolving.
In current Flutter build all assets are in "assets" directory, but time_machine tries to resolve them directly from working directory.

So
/packages/time_machine/data/cultures/en-null.bin
should be 
/assets/packages/time_machine/data/cultures/en-null.bin

**Comment by IoanaAlexandru** [comment]
Check out #25. I believe this is the same issue, the temporary fix is to manually include the `time_machine` data files in the build files.
