### ISSUE TITLE
Readme and Dart 2

### ISSUE THREAD

**Issue by Solido** [Dana-Ferguson/time_machine#4]
You should put this part on the bottom

`dependencies:
  time_machine: "0.7.1"`

And replace it with the last build ... I just copy/paste this and got trapped because the main bold title said Dart 2 ...

**Comment by Dana-Ferguson** [comment]
I will move this to the bottom and change it's wording. If I make the the 'last' build it won't be applicable to Dart 1.24.3 -- I was going to drop this after Dart 2 goes stable. I'm hoping that is this week.

**Comment by Dana-Ferguson** [comment]
I'm assuming you may not be a native english speaker -- I am a native english speaker, so my language construction may not be as good as it can be when consumed by others (case in point, this sentence) -- Anything you notice that looks misleading, or is hard to understand, please let me know.
