### ISSUE TITLE
periodSince is returning 0 on days

### ISSUE THREAD

**Issue by luis-cruzt** [Dana-Ferguson/time_machine#48]
The following example is returning 0 on the days property:

``` 
LocalDate origin = LocalDate.dateTime(DateTime(2020, 11, 1));

LocalDate target = LocalDate.dateTime(DateTime(2021, 10, 1)); 

Period interval = target.periodSince(origin);

print("Days: ${interval.days}"); //Outputs: Days: 0
```

**Comment by Dana-Ferguson** [comment]
```C#
// From NodaTime (reference implementation for Time Machine)
var origin = LocalDate.FromDateTime(new DateTime(2020, 11, 1));
var target = LocalDate.FromDateTime(new DateTime(2021, 10, 1));
var interval = target - origin;

Console.WriteLine($"Days: {interval.Days}"); //Outputs: Days: 0
```

That is the correct output. I'm too tired at the moment to explain why, I'll do some research on this later.
I think it's a mismatch between Period being a 'conceptual' type -vs- a type that exists on the timeline.

Converting the DateTimes to instants, subtracting them, and then converting them to a period returned a better answer.

**Comment by Dana-Ferguson** [comment]
It does return 11 months. Its 11 months, 0 days. Ok, makes sense now.
