### ISSUE TITLE
Flutter build broken : Dart updated to 2.1 dev

### ISSUE THREAD

**Issue by Solido** [Dana-Ferguson/time_machine#5]
@Dana-Ferguson Help !! build is broken 

The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.
Because flutter_native_timezone 1.0.0 requires SDK version >=1.9.0 <2.0.0 and no versions of flutter_native_timezone match >1.0.0 <2.0.0, flutter_native_timezone ^1.0.0 is forbidden.
So, because flutter_calender depends on flutter_native_timezone ^1.0.0, version solving failed.

**Comment by Dana-Ferguson** [comment]
I went ahead and opened an issue for flutter_native_timezone, barring that, I'd just mirror the project locally, update the pubspec.yaml, and then [link to the project on your hard drive](https://www.dartlang.org/tools/pub/dependencies#path-packages).

**Comment by Solido** [comment]
I've acted on precipitation and did not check it wasn't TimeMachine itself ! 
Thank you for going ahead @Dana-Ferguson
