### ISSUE TITLE
Any plans to migrate this package to dart sound null safety

### ISSUE THREAD

**Issue by venkata-reddy-dev** [Dana-Ferguson/time_machine#55]
Hello @Dana-Ferguson , this is a great package 

Any plans to migrate this package to dart sound null safety

**Comment by SteveAlexander** [comment]
I did a rough draft of null safety in this PR

https://github.com/Dana-Ferguson/time_machine/pull/50

It probably doesn’t fully work yet. I did it more as an exploration in what would be necessary for supporting null safety in this quite complex package. 

I’d be happy to work on this further, but I’d like to have some conversation with the package maintainers first, to make sure I’m on the right track with the changes I’ve made.

**Comment by kuhnroyal** [comment]
Really need this for the openapi-generator.

**Comment by SteveAlexander** [comment]
I've been polishing up the null-safety PR. As of now, there are no analyzer errors on the branch (pedantic analysis rules), 10000 tests pass and one test fails. I'm looking into the failing test now.

So, this is almost ready for review.

**Comment by benjdero** [comment]
@SteveAlexander I wanted to say thank you for your work. This is one of the very few dependencies that hold my projects to move forward with null safety.

**Comment by SteveAlexander** [comment]
Thanks @benjdero. I know there's a number of people keen to see a null-safe release.

I've been talking with @Dana-Ferguson, author of this package, who is reviewing the null-safety PR. I'm hopeful we'll be moving this forward, and doing a new time_machine release in the near future.

**Comment by benjdero** [comment]
@SteveAlexander Sure. No pressure. I just wanted to say thank you.

**Comment by brouwer** [comment]
Noticed the PR was merged, can we get a new release on pub.dev too? @Dana-Ferguson

**Comment by markbeij** [comment]
@kuhnroyal, is this issue still what you are waiting for in order to make operapi-generator generate null-safe code?
@Dana-Ferguson, when can we expect this issue to be solved?

**Comment by kuhnroyal** [comment]
Yea, the time_machine option in the dart-dio generator is still waiting on this to be migrated.
