### ISSUE TITLE
io.Platform.localeName is C.UTF-8 on github actions server

### ISSUE THREAD

**Issue by SteveAlexander** [Dana-Ferguson/time_machine#57]
@rich-j originally noted this issue against https://github.com/Dana-Ferguson/time_machine/pull/50

I'm re-filing it as an issue, seeing as that PR has now been merged.

It seems that GitHub actions running on ubuntu doesn't have a valid locale defined so calling TimeMachine.initialize(); fails with:

```
Failed to load "test/a_test.dart": Null check operator used on a null value
  package:time_machine/src/platforms/vm.dart 99:39  TimeMachine.initialize
```

Lines 96-100

```dart
   // Default Culture
   var cultureId = io.Platform.localeName.split('.').first.replaceAll('_', '-');
   Culture? culture = await Cultures.getCulture(cultureId);
   ICultures.currentCulture = culture!;       // <-- the non-null assertion here fails
   // todo: remove Culture.currentCulture
```

explicitly assumes the culture is found. It also has a todo to possibly remove this.

On that OS, `io.Platform.localeName` is `C.UTF-8`.

A bit of research on this suggests that a reasonable thing to do for a platform locale of `C` is to use `en.US`

See the first full answer here: https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do

@rich-j do you think adding a special case here for a locale of `C` and using `en.US` would meet your needs?

**Comment by rich-j** [comment]
@SteveAlexander the special case would work but we would prefer the ability to override the initialization - particularly for testing. The `initialize` method already accepts a map that allows overriding the `timeZone`. How about a `culture` override so our tests can initialize like so:

``` dart
await TimeMachine.initialize({"timeZone": "America/Chicago", "culture": "en-US" });
```

This will remove an unknown environment value from our tests.

Looking at the code the override seemed fairly straightforward so I went ahead and made PR #58

**Comment by SteveAlexander** [comment]
I think both would be good — the "C" locale is obviously a thing that occurs, so we should support that without crashing.

As a separate issue, being able to explicitly specify a default locale on init seems like a good feature too.
