### ISSUE TITLE
Package uses device time instead of the timezones actual time

### ISSUE THREAD

**Issue by shabeenabarde** [Dana-Ferguson/time_machine#60]
**So I am trying to get Africa/Nairobi's time because my app needs a country's exact time to work, and if the user's device is 2 minutes infront or behind, it won't work. I personally needs the exact time for my API's timestamp.

So I tried to use this package but it still prints out the device time and calculates the time according to the device time instead of the timezone's time. Why is that?

Below are the functions that I am using :**

/* Time Machine testing */

  Future timeMachineMain() async {
    try {
      // Sets up timezone and culture information
      await TimeMachine.initialize({
        'rootBundle': rootBundle,
      });
      print('Hello, ${DateTimeZone.local} from the Dart Time Machine!\n');

      var tzdb = await DateTimeZoneProviders.tzdb;
      var paris = await tzdb['Europe/Paris'];
      var nrb = await tzdb['Africa/Nairobi'];

      var now = Instant.now();

      print('Basic');
      print('UTC Time: $now');
      print('Local Time: ${now.inLocalZone()}');
      print('Paris Time: ${now.inZone(paris)}\n');
      print('nrb Time: ${now.inZone(nrb)}\n');

      print('Formatted');
      print('UTC Time: ${now.toString('dddd yyyy-MM-dd HH:mm')}');
      print(
          'Local Time: ${now.inLocalZone().toString('dddd yyyy-MM-dd HH:mm')}\n');

      var french = await Cultures.getCulture('fr-FR');
      print('Formatted and French ($french)');
      print('UTC Time: ${now.toString('dddd yyyy-MM-dd HH:mm', french)}');
      print(
          'Local Time: ${now.inLocalZone().toString('dddd yyyy-MM-dd HH:mm', french)}\n');

      print('Parse French Formatted ZonedDateTime');

      // without the 'z' parsing will be forced to interpret the timezone as UTC
      var localText =
          now.inLocalZone().toString('dddd yyyy-MM-dd HH:mm z', french);

      var localClone = ZonedDateTimePattern.createWithCulture(
              'dddd yyyy-MM-dd HH:mm z', french)
          .parse(localText);

      print(localClone.value);
    } catch (error, stack) {
      print(error);
      print(stack);
    }
  }

How can I achieve to get the time without using the local device time??

**Comment by SteveAlexander** [comment]
If I understand right, you want to get time from some reliable source, rather than from a device like a phone. This is because the phone might have its clock set incorrectly. Is that right?

**Comment by shabeenabarde** [comment]
@SteveAlexander Yes thats right.

I tried using the ntp package, but it is not reliable as for some networks it was giving me the Error of "SocketException: OS Error: Connection timed out, errno = 110, address = dns.google.com, port = 44198" ,
and when I tried to access dns.google.com from the network it was giving me the error, i was not able to access it. 

While, the networks that was working with the ntp package, i was able to access dns.google.com from the browser, so i am in a bit of a dilemma here and my client is waiting for me to deliver the app. I have no idea what to do..

**Comment by SteveAlexander** [comment]
Okay, so I don't think this package, time_machine, will help you a lot with this. The time_machine package uses the phone's clock to know what the current time is. So, if the phone's clock has the right time, time_machine will work with the right time. But, if the phone's clock is wrong, then time_machine will also give the wrong time.

We can't really talk about the ntp package here — I expect they have an issue tracker or something, which is for talking about that.

But I do notice that the error you mentioned is about DNS, not NTP. That is, looking up domain names (any domain names), not looking up internet time. I hope that helps as you look into this problem.

If you agree with me that this isn't a problem with the time_machine package, I'll close this issue.

**Comment by shabeenabarde** [comment]
@SteveAlexander  Yes, you can close this issue. I just thought maybe this package takes the timezone's time. Anyhoo, thank you for responding :)
