### ISSUE TITLE
Continue supporting VM processing without Flutter

### ISSUE THREAD

**Issue by rich-j** [Dana-Ferguson/time_machine#63]
PR #52 effectively makes Flutter a requirement for non-web use (web support uses different code). The PR extended the non-web platform checks that require a Flutter `rootBundle` from `isIOS`, `isAndroid`, `isFuchsia` to now also include `isMacOS`, `isWindows`, `isLinux`. This list effectively makes all non-web code require Flutter. This breaks testing of our common library that still supports AngularDart.

Yes, probably all new users will be using Flutter so the default path of requiring a `rootBundle` is reasonable. We still need some way to use `_VirtualMachineIO()` for testing without Flutter. How about an initialization flag `useVirtualMachineIO`?

In the `initialize()` function of `vm.dart`:
``` dart
if (args['useVirtualMachineIO'] == true) {
  PlatformIO.local = _VirtualMachineIO();
} else {
  if (args['rootBundle'] == null) throw Exception("Pass in the rootBundle from 'package:flutter/services.dart';");
  PlatformIO.local = _FlutterMachineIO(args['rootBundle']);
}
```
This initialization code will allow any VM platform to opt-in to use the original non Flutter IO.

**Comment by SteveAlexander** [comment]
That’s a great point!

Would you mind making a PR that improves things?

**Comment by rich-j** [comment]
I just noticed that this bug wasn't closed. There is now a `testing` flag that when true will use the VirtualMachingIO - which means testing doesn't require Flutter. It's used like this:

```dart
await TimeMachine.initialize({"timeZone": "America/Chicago", "culture": "en-US", "testing": true });
```
